language: erlang
otp_release:
  - 19.2
install:
  - make
  - ./rebar3 update
script:
  - make test
  - make with-partisan-test
  - make scale-test
  - make large-scale-test
  - make partisan-scale-test
  - make partisan-large-scale-test
  - exit 0
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false