language: erlang
otp_release:
  - 19.2
install:
  - make
  - ./rebar3 update
script:
  - make test
  - make large-membership-test
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false
