apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unir
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tag: unir
    spec:
      containers:
      - name: unir
        image: gcr.io/partisan-203021/unir:v1
        imagePullPolicy: IfNotPresent
        restartPolicy: Never
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
